version: "3.9"

services:
  db:
    container_name: db
    hostname: db
    image: sameersbn/redis:4.0.9-2
    command: --port 6969
    ports:
      - "6969:6969"
    expose:
      - "6969"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always
    networks:
      - app-hash-tier
  web:
    build: .
    command: python main.py
    networks:
      - app-hash-tier
    depends_on:
      - db

networks:
  app-hash-tier:
    driver: bridge
