version: "3.9"

services:
  db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '22869:22869'
    command: redis-server --save 20 1 --loglevel warning --requirepass underwaterlove
    volumes:
      - /data/tips/cache:/data
    networks:
      - app-hash-tier
  web:
    build: .
    command: python main.py
    networks:
      - app-hash-tier
    depends_on:
      - db

networks:
  app-hash-tier:
    driver: bridge
